### ISSUE TITLE
usberror in mac

### ISSUE THREAD

**Issue by novia713** [armijnhemel/py3buddy#2]
```
$ sudo python3 py3buddydemo.py -c py3buddy.config
Password:

py3buddy demo scripts

Demo 1: PANIC!

Traceback (most recent call last):
  File "py3buddydemo.py", line 166, in <module>
    main(sys.argv)
  File "py3buddydemo.py", line 149, in main
    panic(ibuddy,10)
  File "py3buddydemo.py", line 16, in panic
    ibuddy.reset()
  File "/Users/leandro/git/py3buddy/py3buddy.py", line 171, in reset
    self.dev.ctrl_transfer(0x21, 0x09, 2, 1, setupmsg)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 1034, in ctrl_transfer
    self._ctx.managed_claim_interface(self, interface_number)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
```

**Comment by armijnhemel** [comment]
Gosh, I don't have an OS X device to reproduce this, so I am a bit at a loss how to fix it. It is clear to me what the error is though. I will try to see if I can find someone with a Mac who's willing to help out.

**Comment by novia713** [comment]
i can do any test you need, if you want
feel free to contact me
