### ISSUE TITLE
usb.core.NoBackendError

### ISSUE THREAD

**Issue by sommoMicc** [armijnhemel/py3buddy#6]
`python py3buddydemo.py -c py3buddy.config

py3buddydemo.py:127: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.

  config.readfp(configfile)
Traceback (most recent call last):
  File "py3buddydemo.py", line 176, in <module>
    main(sys.argv)
  File "py3buddydemo.py", line 150, in main
    ibuddy = py3buddy.iBuddy(buddy_config)
  File "C:\Users\mikit\OneDrive\Documenti\GIT\py3buddy\py3buddy\py3buddy.py", line 138, in __init__
    idProduct=buddy_config['productid'])
  File "C:\Users\mikit\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available`

**Comment by armijnhemel** [comment]
There are two things here: one is the deprecation warning (I will remove that error soon).

The other one is probably because of a wrong product id. Which iBuddy do you have? Red/yellow wings? If so, set the product id in the configuration file to 0001. This is something I have to rework.

**Comment by sommoMicc** [comment]
Hi,
don't care about the deprecation warning

I've double-checked and productid=0001 was already present in the configuration file loaded. Also, as you can see from the screenshot below, iBuddy is showing up in device manager.
Is it possible that some required software is missing from my computer?

![Proprietà - Dispositivo compatibile HID 20_11_2019 15_57_41](https://user-images.githubusercontent.com/20479709/69249645-81e98000-0bae-11ea-9063-bf226a363bf1.png)

**Comment by sommoMicc** [comment]
A quick update: this problem seems to happen only in windows. In fact, I tried running py3buddy on Ubuntu 18.04 (on the same computer, with i-Buddy plugged on the same USB port) and it worked

**Comment by armijnhemel** [comment]
Unfortunately I have no Windows machine to test or debug :(

**Comment by mnavarromugas** [comment]
In windows you should install pyusb and this https://sourceforge.net/projects/libusb/files/libusb-1.0/libusb-1.0.21/libusb-1.0.21.7z/download.

on 64-bit Windows, copy MS64\dll\libusb-1.0.dll into C:\windows\system32. If on 32-bit windows, copy MS32\dll\libusb-1.0.dll into C:\windows\SysWOW64

**Comment by mnavarromugas** [comment]
Got this error

.\py3buddydemo.py:127: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(configfile)
Traceback (most recent call last):
  File ".\py3buddydemo.py", line 176, in <module>
    main(sys.argv)
  File ".\py3buddydemo.py", line 150, in main
    ibuddy = py3buddy.iBuddy(buddy_config)
  File "D:\Code\py3buddy-master\py3buddy\py3buddy.py", line 147, in __init__
    if self.dev.is_kernel_driver_active(0) is True:
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 1061, in is_kernel_driver_active
    self._ctx.managed_open()
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 120, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "D:\Python\Python37\lib\site-packages\usb\backend\libusb1.py", line 786, in open_device
    return _DeviceHandle(dev)
  File "D:\Python\Python37\lib\site-packages\usb\backend\libusb1.py", line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "D:\Python\Python37\lib\site-packages\usb\backend\libusb1.py", line 593, in _check
    raise NotImplementedError(_strerror(ret))
NotImplementedError: Operation not supported or unimplemented on this platform
